# Generated by Django 3.2.4 on 2022-04-26 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='products.productlisting'),
        ),
    ]
