# Generated by Django 3.2.4 on 2022-04-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220425_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='product_active_period',
            field=models.IntegerField(default=30, null=True),
        ),
    ]
