# Generated by Django 3.2.4 on 2022-04-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productlisting_product_active_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='product_active_period',
            field=models.DateField(null=True),
        ),
    ]
