# Generated by Django 3.2.4 on 2022-04-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productlisting_product_active_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='product_active_period',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='active_period',
            field=models.DateField(null=True),
        ),
    ]
