# Generated by Django 3.2.4 on 2022-03-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('card_num', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('card_code', models.IntegerField()),
                ('expire_month', models.CharField(max_length=255)),
                ('expire_year', models.IntegerField()),
                ('card_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('listing_id', models.IntegerField()),
                ('date', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('payment', models.FloatField()),
            ],
        ),
    ]
