# Generated by Django 3.2.4 on 2022-03-23 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('street_num', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller_infos', serialize=False, to='auth.user')),
                ('routing_number', models.CharField(max_length=255)),
                ('account_number', models.IntegerField()),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ZipcodeInfo',
            fields=[
                ('zipcode', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('state_id', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('density', models.FloatField()),
                ('county_name', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyer_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='buyer_infos', serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Bigender', 'Bigender'), ('Polygender', 'Polygender'), ('Non-binary', 'Non-binary'), ('Agender', 'Agender'), ('Genderfluid', 'Genderfluid'), ('Genderqueer', 'Genderqueer')], max_length=255)),
                ('age', models.IntegerField()),
                ('billing_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='users.address')),
                ('home_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_address', to='users.address')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.zipcodeinfo'),
        ),
        migrations.CreateModel(
            name='LocalVendor',
            fields=[
                ('vendor_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vendor_infos', serialize=False, to='users.seller')),
                ('business_name', models.CharField(max_length=255)),
                ('customer_service_num', models.CharField(max_length=255)),
                ('business_address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_address', to='users.address')),
            ],
        ),
    ]
